services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
